name: Deploy Theme

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allows the action to create a release.
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        run: |
          sudo apt-get install -y librsvg2-bin
          pwsh -File ./tools/build.ps1 -verbose -f -a pink
          pwsh -File ./tools/build.ps1 -verbose -f -a purple
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-artifact
          path: ./build/*.*
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pwsh -File ./tools/changelog.ps1 -noheader > ./release_notes.txt
          gh release create ${{ github.ref_name }} $(find ./build -type f) \
            --title ${{ github.ref_name }} \
            --notes-file ./release_notes.txt \
            --draft=false \
            --prerelease=false \
            --verify-tag
