name: Build Packages

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build package
        shell: pwsh
        run: |
          sudo apt-get install -y librsvg2-bin
          ./scripts/build.ps1 -accent pink -force
          ./scripts/build.ps1 -accent purple -force
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build/*.*
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}

  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/')
    # && github.repository == 'dracula/mixplorer'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - shell: pwsh
        run: |
          $files = resolve-path ./build/*.* -relative -ea:0
          if ($files) {
            ./scripts/changelog.ps1 -noheader | out-file ./changes.md
            gh release create ${{ github.ref_name }} $files -F ./changes.md --generate-notes --verify-tag
          } else {
            [System.Console]::WriteLine("cannot find files on ./build"); exit 1
          }
