name: build

on:
  push:
    paths:
      - '**.md'
      - 'bin/**'
      - 'res/**'
      - 'scripts/**'
      - 'screenshot.png'
      - '.github/**/**.yml'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions: write-all
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build package
        shell: pwsh
        run: |
          sudo apt-get install -y librsvg2-bin
          ./scripts/build.ps1 -a pink -f
          ./scripts/build.ps1 -a purple -f
      - name: Upload artifact
        # if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build/*.*
          retention-days: 7
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'sionta/mixplorer'
        shell: pwsh
        run: |
          $files = resolve-path ./build/*.* -relative -ea:0
          if ($files) {
            $tag = "${{ github.ref_name }}"
            $version = $tag -replace '^v', ''
            $changelog = get-content ./changelog.md -ea:0
            if ($changelog -match "^##\s\[$version\]") {
              ./scripts/changelog.ps1 -n | out-file ./changes.md
              gh release create $tag $files -F ./changes.md --verify-tag
            } else {
              gh release create $tag $files --generate-notes --verify-tag
            }
          } else {
            "cannot find files on ./build"; exit 1
          }
          exit $LASTEXITCODE
