name: Build Packages

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

permissions: write-all
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build package
        shell: pwsh
        run: |
          sudo apt-get install -y librsvg2-bin
          ./scripts/build.ps1 -accent pink -force
          ./scripts/build.ps1 -accent purple -force
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build/*.*
        # if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $files = resolve-path ./build/*.* -relative -ea:0
          if ($files) {
            ./scripts/changelog.ps1 -noheader | out-file ./changes.md
            if (test-path ./changes.md -type leaf) {
              gh release create ${{ github.ref_name }} $files -F ./changes.md --generate-notes --verify-tag
            } else {
              gh release create ${{ github.ref_name }} --generate-notes --verify-tag
            }
          } else {
            write-host "cannot find files on ./build"
            exit 1
          }
        continue-on-error: false
