name: Release Package

on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write # allows the action to create a release.
    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        run: |
          sudo apt-get install -y librsvg2-bin
          pwsh -File ./tools/build.ps1 -f -a pink
          pwsh -File ./tools/build.ps1 -f -a purple
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pwsh -File ./tools/changelog.ps1 -noheader > ./release_notes.txt
          gh release create ${{ github.ref }} $(find ./build -type f) \
            -t "Release ${{ github.ref }}" \
            --notes-file ./release_notes.txt \
            --draft=false \
            --prerelease=false \
